<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>James Routley | Feed</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="../styles.css"
      media="screen"
    />
  </head>
  <body>
    <a href="/index.html">Back</a>
    <a href="https://openai.com/blog/march-20-chatgpt-outage">Original</a>
    <h1>March 20 ChatGPT outage: Here’s what happened</h1>
    
    <div id="readability-page-1" class="page"><div id="content"><!--[--><div><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div><div><div><div><div><div><p>We took ChatGPT offline earlier this week due to a bug in an open-source library which allowed some users to see titles from another active user’s chat history. It’s also possible that the first message of a newly-created conversation was visible in someone else’s chat history if both users were active around the same time.</p><p>The bug is now patched. We were able to restore both the ChatGPT service and, later, its chat history feature, with the exception of a few hours of history. As promised, we’re publishing more <a href="#technical-details" rel="noopener noreferrer">technical details</a> of this problem below.</p><p>Upon deeper investigation, we also discovered that the same bug may have caused the unintentional visibility of payment-related information of 1.2% of the ChatGPT Plus subscribers who were <strong>active</strong> during a specific nine-hour window. In the hours before we took ChatGPT offline on Monday, it was possible for some users to see another <strong>active</strong> user’s first and last name, email address, payment address, the last four digits (only) of a credit card number, and credit card expiration date. Full credit card numbers were not exposed at any time. </p><p>We believe the number of users whose data was actually revealed to someone else is extremely low. To access this information, a ChatGPT Plus subscriber would have needed to do one of the following:</p><ul><li>Open a subscription confirmation email sent on Monday, March 20, between 1 a.m. and 10 a.m. Pacific time. Due to the bug, some subscription confirmation emails generated during that window were sent to the wrong users. These emails contained the last four digits of another user’s credit card number, but full credit card numbers did not appear. It’s possible that a small number of subscription confirmation emails might have been incorrectly addressed prior to March 20, although we have not confirmed any instances of this.</li><li>In ChatGPT, click on “My account,” then “Manage my subscription” between 1 a.m. and 10 a.m. Pacific time on Monday, March 20. During this window, another <strong>active</strong> ChatGPT Plus user’s first and last name, email address, payment address, the last four digits (only) of a credit card number, and credit card expiration date might have been visible. It’s possible that this also could have occurred prior to March 20, although we have not confirmed any instances of this.</li></ul><p>We have reached out to notify affected users that their payment information may have been exposed. We are confident that there is no ongoing risk to users’ data. </p><p>Everyone at OpenAI is committed to protecting our users’ privacy and keeping their data safe. It’s a responsibility we take incredibly seriously. Unfortunately, this week we fell short of that commitment, and of our users’ expectations. We apologize again to our users and to the entire ChatGPT community and will work diligently to rebuild trust.<br/></p></div></div></div></div></div></div><!----><!----><!----><!----></div><div><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div><div><div><div><div><div><p>The bug was discovered in the Redis client open-source library, redis-py. As soon as we identified the bug, we reached out to the Redis maintainers with a patch to resolve the issue. Here’s how the bug worked: </p><ul><li>We use Redis to cache user information in our server so we don’t need to check our database for every request. </li><li>We use Redis Cluster to distribute this load over multiple Redis instances. </li><li>We use the redis-py library to interface with Redis from our Python server, which runs with Asyncio. </li><li>The library maintains a shared pool of connections between the server and the cluster, and recycles a connection to be used for another request once done.</li><li>When using Asyncio, requests and responses with redis-py behave as two queues: the caller pushes a request onto the incoming queue, and will pop a response from the outgoing queue, and then return the connection to the pool.</li><li>If a request is canceled after the request is pushed onto the incoming queue, but before the response popped from the outgoing queue, we see our bug: the connection thus becomes corrupted and the next response that’s dequeued for an unrelated request can receive data left behind in the connection. </li><li>In most cases, this results in an unrecoverable server error, and the user will have to try their request again. </li><li>But in some cases the corrupted data happens to match the data type the requester was expecting, and so what gets returned from the cache appears valid, even if it belongs to another user.</li><li>At 1 a.m. Pacific time on Monday, March 20, we inadvertently introduced a change to our server that caused a spike in Redis request cancellations. This created a small probability for each connection to return bad data.</li></ul><p>This bug only appeared in the Asyncio redis-py client for Redis Cluster, and has now been fixed.<br/></p></div></div></div></div></div></div><!----><!----><!----><!----></div><div><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div><div><div><div><div><div><p>As our investigation wraps up, supporting and informing our users is our top priority. </p><p>We have taken the following actions to improve our systems:</p><ul><li>Extensively tested our fix to the underlying bug.</li><li>Added redundant checks to ensure the data returned by our Redis cache matches the requesting user.</li><li>Programatically examined our logs to make sure that all messages are only available to the correct user.</li><li>Correlated several data sources to precisely identify the affected users so that we can notify them.</li><li>Improved logging to identify when this is happening and fully confirm it has stopped.</li><li>Improved the robustness and scale of our Redis cluster to reduce the likelihood of connection errors at extreme load.<br/></li></ul></div></div></div></div></div></div><!----><!----><!----><!----></div><div><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><div><div><div><div><div><p>The Redis open-source maintainers have been fantastic collaborators, swiftly addressing the bug and rolling out a patch. Redis, along with other open-source software, plays a crucial role in our research efforts. Their significance cannot be understated—we would not have been able to scale ChatGPT without Redis. We’re dedicated to continually supporting and contributing to the Redis community.<br/></p></div></div></div></div></div><!----><!----><!----><!----></div><!--]--></div></div>
  </body>
</html>
